version: '3.4'
services:
  nginx:
    image: nginx:1.17.6-alpine
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
  api:
    build:
      context: .
      target: development
    image: johnmerga/erap-backend_api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    ports:
      # - 5001:5000
      - 9229:9229 # for debugging
    env_file:
      - .env.test
  db:
    image: mongo
    volumes:
      - db:/data/db
volumes:
  db: