version: '3.4'
services:
  nginx:
    image: nginx:1.17.6-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
  api:
    build:
      context: .
      target: production
    image: johnmerga/erap-backend_api
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mongo